"""
Application Settings
====================
Single source of truth for all configuration.
Uses pydantic-settings to load from environment / .env file.
"""

from functools import lru_cache
from typing import List

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    openai_api_key: str = Field(..., description="OpenAI API key")
    openai_model: str = Field("gpt-4o-mini", description="Chat/generation model")
    embedding_model: str = Field("text-embedding-3-small", description="Embedding model")

    vectorstore_path: str = Field("vector_store", description="FAISS index directory")
    upload_dir: str = Field("data/raw", description="Uploaded files root directory")
    max_file_size_mb: int = Field(50, description="Max upload file size in MB")

    chunk_size: int = Field(800, description="Default chunk size (chars) - overridden per format")
    chunk_overlap: int = Field(150, description="Default chunk overlap (chars)")

    top_k: int = Field(8, description="Default retrieved chunks per query")
    use_multi_query: bool = Field(True, description="Enable MultiQueryRetriever")
    use_hybrid_search: bool = Field(True, description="Enable BM25+vector hybrid search")
    hybrid_bm25_weight: float = Field(0.3, description="BM25 weight in hybrid ensemble (0-1)")
    rerank_threshold: float = Field(
        0.30,
        description="EmbeddingsFilter similarity threshold (0.30 is a safe default for text-embedding-3-small)",
    )
    query_cache_ttl_seconds: int = Field(300, description="TTL in seconds for query result cache (0 = disabled)")
    multi_query_num_queries: int = Field(2, description="Query variants generated by MultiQueryRetriever")
    compound_query_top_k: int = Field(4, description="Top-k used per clause when a query is split into focused sub-questions")
    answer_max_tokens: int = Field(700, description="Max completion tokens for single-question answers")
    compound_answer_max_tokens: int = Field(900, description="Max completion tokens for compound question answers")

    langchain_tracing_v2: bool = Field(False, description="Enable LangSmith tracing")
    langchain_api_key: str = Field("", description="LangSmith API key")
    langchain_project: str = Field("finrag-engine", description="LangSmith project name")

    supabase_url: str = Field("", description="Supabase project URL")
    supabase_anon_key: str = Field("", description="Supabase anon/public key")
    supabase_jwt_secret: str = Field("", description="Supabase JWT secret for token validation")

    app_env: str = Field("development", description="Environment: development | production")
    log_level: str = Field("INFO", description="Logging level")
    cors_origins: List[str] = Field(
        default_factory=list,
        description="Allowed CORS origins (comma-separated in .env)",
    )

    @field_validator("cors_origins", mode="before")
    @classmethod
    def _parse_cors_origins(cls, v: object) -> List[str]:
        if isinstance(v, str):
            return [origin.strip() for origin in v.split(",") if origin.strip()]
        return v  # type: ignore[return-value]

    @property
    def max_file_size_bytes(self) -> int:
        return self.max_file_size_mb * 1024 * 1024

    @property
    def is_development(self) -> bool:
        return self.app_env.lower() == "development"


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    """Cached Settings singleton - reads .env exactly once per process."""
    return Settings()
